# Generated by Django 5.1.4 on 2025-01-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goruntu_isleme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default='İsim yok', max_length=255),
        ),
    ]
