# Generated by Django 5.1.4 on 2025-01-04 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goruntu_isleme', '0002_video_description_video_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='uploaded_at',
            new_name='uploaded_date',
        ),
    ]
