# Generated by Django 5.1.4 on 2025-01-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goruntu_isleme', '0004_rename_uploaded_date_video_upload_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('coordinates', models.JSONField()),
            ],
        ),
    ]
