# Generated by Django 5.1.4 on 2025-01-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goruntu_isleme', '0006_route_created_at_alter_route_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fuel_capacity_liters', models.FloatField()),
                ('flight_range_km', models.FloatField()),
                ('payload_capacity_kg', models.FloatField()),
            ],
        ),
    ]
