# Generated by Django 5.1.4 on 2025-01-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goruntu_isleme', '0007_drone'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='camera_type',
            field=models.CharField(default='Kamera Türü Giriniz', max_length=100),
        ),
        migrations.AddField(
            model_name='drone',
            name='iletim_araligi',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='drone',
            name='max_ucus_sure',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='drone',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='drone_photos/'),
        ),
        migrations.AddField(
            model_name='drone',
            name='sicaklik',
            field=models.CharField(default='Sıcaklık Giriniz', max_length=100),
        ),
        migrations.AlterField(
            model_name='drone',
            name='flight_range_km',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='drone',
            name='fuel_capacity_liters',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='drone',
            name='name',
            field=models.CharField(default='İsim Giriniz', max_length=100),
        ),
        migrations.AlterField(
            model_name='drone',
            name='payload_capacity_kg',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(default='Açıklama Giriniz'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(default='İsim Giriniz', max_length=255),
        ),
    ]
