# Generated by Django 5.1.4 on 2025-01-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goruntu_isleme', '0008_drone_camera_type_drone_iletim_araligi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drone',
            name='fuel_capacity_liters',
        ),
        migrations.AddField(
            model_name='drone',
            name='guc_turu',
            field=models.CharField(default='Güç Türü Giriniz', max_length=100),
        ),
    ]
