# Generated by Django 5.1.4 on 2025-01-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goruntu_isleme', '0009_remove_drone_fuel_capacity_liters_drone_guc_turu'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='koruma_derecesi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='drone',
            name='flight_range_km',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='drone',
            name='iletim_araligi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='drone',
            name='max_ucus_sure',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='drone',
            name='payload_capacity_kg',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
