# Generated by Django 5.1.4 on 2025-01-12 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goruntu_isleme', '0010_drone_koruma_derecesi_alter_drone_flight_range_km_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drone',
            old_name='flight_range_km',
            new_name='flight_range',
        ),
        migrations.RenameField(
            model_name='drone',
            old_name='payload_capacity_kg',
            new_name='payload_capacity',
        ),
    ]
